DROP TABLE IF EXISTS pizza_sales;
CREATE TABLE pizza_sales (
    pizza_id int,
	order_id int,
	pizza_name_id varchar(150),
	quantity int,
	order_date date,
	order_time time,
	unit_price decimal(8,2),
	total_price decimal(8,2),
    pizza_size  varchar(10),
	pizza_category varchar(50),
	pizza_ingredients varchar(200),
	pizza_name varchar(100)
)

--EDA
select * from pizza_sales

select count(*) from pizza_sales

select count(distinct pizza_id) from pizza_sales
select count(distinct order_id) from pizza_sales

select distinct(pizza_category) from pizza_sales
select distinct(pizza_name) from pizza_sales
select distinct(pizza_name_id) from pizza_sales
select distinct(pizza_size) from pizza_sales

select max(unit_price) from pizza_sales
select min(unit_price) from pizza_sales

---

--BUSINESS QUESTIONS

--1.Total Revenue generated by pizza store
select sum(total_price) as Total_Revenue
from pizza_sales


--2.Average order value 
select 
 sum(total_price)/count(distinct order_id) as avg_order_value
from pizza_sales


--3.Total pizzas sold by the store.
select
sum(quantity) as total_pizzas_sold
from pizza_sales


--4.tTotal pizzas orders
select 
count(distinct order_id) as total_orders
from pizza_sales


--5.Find out average number of pizzas being sold per order.
select 
 cast(cast(sum(quantity) as decimal(10,2))/
 cast(count(distinct order_id) as decimal(10,2))as decimal(10,2)) as Avg_pizza_sold
from pizza_sales


--6.Daily Trends for Total Orders
select 
 trim(to_char(order_date,'day')) as order_day,
 count(distinct order_id) as total_orders
from pizza_sales
group by 1,extract(dow from order_date)
order by extract(dow from order_date)


--7.Monthly Trends for Total Orders
select 
 trim(to_char(order_date,'month')) as order_month,
 count(distinct order_id) as total_orders
from pizza_sales
group by 1,extract(month from order_date)
order by extract(month from order_date)


--8.Find out percentage of sales by pizza category
select 
 pizza_category,
 sum(unit_price) as total_revenue,
 cast(sum(unit_price)*100/
 (select sum(unit_price) from pizza_sales) as decimal(10,2)) as sales_percent
from pizza_sales
group by 1


--9.Find out percentage of sales by pizza size.
select 
 pizza_size,
 sum(unit_price) as total_revenue,
 cast(sum(unit_price)*100/
 (select sum(unit_price) from pizza_sales) as decimal(10,2)) as sales_percent
from pizza_sales
group by 1
order by 3 desc


--10.Top 5 Pizzas
select 
 pizza_name,
 sum(total_price) as total_revenue
from pizza_sales
group by 1
order by 2 desc
limit 5


--11.Bottom 5 Pizzas
select 
 pizza_name,
 sum(total_price) as total_revenue
from pizza_sales
group by 1
order by 2 asc
limit 5


--12.Which size is most popular ?
select 
 pizza_size,
 sum(quantity) as most_sold
from pizza_sales
group by 1
order by 2 desc


--13.When are pizzas selling the most?(Peak hours)
select
 extract(hour from order_time) as peak_time,
 count(order_id) as total_orders
from pizza_sales
group by extract(hour from order_time) 
order by 2 desc


--14.Top 3 pizzas per category (window functions).
WITH pizza_revenue AS (
    SELECT
        pizza_category,
        pizza_name,
        SUM(total_price) AS total_revenue
    FROM pizza_sales
    GROUP BY pizza_category, pizza_name
),
ranked_pizzas AS (
    SELECT
        pizza_category,
        pizza_name,
        total_revenue,
        RANK() OVER (PARTITION BY pizza_category ORDER BY total_revenue DESC  ) AS rnk
    FROM pizza_revenue
)
SELECT
    pizza_category,
    pizza_name,
    total_revenue,
    rnk
FROM ranked_pizzas
WHERE rnk <= 3
ORDER BY pizza_category, rnk;




